### ISSUE TITLE
Google Chrome Error

### ISSUE THREAD

**Issue by gazjoy** [stevenwanderski/bxslider-3#1]
Hi I am getting the following error in Chrome:

<pre>
jquery.bxSlider.js:602Uncaught TypeError: Object has no method 'unwrap'.
</pre>

I am using Chrome 13.0.782.112 on Mac OSX.

Any ideas?
GazJoy.

**Comment by gazjoy** [comment]
Hi there, any updates on this?

**Comment by stevenwanderski** [comment]
I have not seen any issues in Chrome. Can you send a link to the problem page?

**Comment by gazjoy** [comment]
Sorry rookie mistake, wasn't linking to the files correctly, all is good.
