### ISSUE TITLE
Images are ~20 pixels to the right on first loop through

### ISSUE THREAD

**Issue by brunzino** [stevenwanderski/bxslider-3#103]
...and then after the first loop through, the image 'pops' to the left (correct?) position and looks good. 

Using Chrome17 and FireFox10

**Comment by brunzino** [comment]
adding inline style tag with "padding: 0; margin: 0;" to the ul solved this problem

**Comment by jaspreet2012** [comment]
thanks to that.... i wa struggling for 2 weeks with this
