### ISSUE TITLE
Slide a grid of thumbs?

### ISSUE THREAD

**Issue by ghost** [stevenwanderski/bxslider-3#14]
Hi,

I love BXSlider it's great, thank you for the work! This is my first time using Github so i apologise if this is the wrong place to be asking such questions like this...

Is it possible to slide a grid of thumbnails/text? For example, this: http://bxslider.com/examples/display-move-multiple-slides-once-example-two but a 3x3 grid instead of on just a single row?

Any help is much appreciated,

Thanks!

**Comment by markpopkes** [comment]
This is possible, but you need to do a bit of tweaking. Since bxSlider recognizes "slides", you'll need to put each 3x3 grid in its own "slide" container, like so: 

``` html
<div id="slider1">
    <div class="slide">
        <!-- insert 3x3 grid here -->
    </div>
    <div class="slide">
        <!-- insert 3x3 grid here -->
    </div>
    <div class="slide">
        <!-- insert 3x3 grid here -->
    </div>
</div>

```

**Comment by ghost** [comment]
thanks!
