### ISSUE TITLE
Rocky/Not Smooth Animations/Transitions in Google Chrome

### ISSUE THREAD

**Issue by jamezamm** [stevenwanderski/bxslider-3#151]
Transitions between slides in bx-slider appear to be smooth in all browsers but not in Google Chrome. Thanks.

**Comment by jamezamm** [comment]
This is an example(View this in Google Chrome): <a target="_blank" href="http://www.yw4jc.com">Click Here</a>

**Comment by fabyeah** [comment]
+1

I have the same problem. Version 4.0. Smooth in IE10, FF, Safari. Choppy in Chrome. :(
I have fullscreen image backgrounds.
