### ISSUE TITLE
hideControlOnEnd does not work

### ISSUE THREAD

**Issue by tba6440** [stevenwanderski/bxslider-3#17]
hideControlOnEnd does not work with displaySlideQty:5 and moveSlideQty:5  

Example here: http://kummerpartner.xuul.org/projekte/wohnen-arbeiten/

Quick and dirty solution:

On ~ line 1149 under // check next

Replace this:
if(currentSlide == lastSlide)

with something like this:
if($children.length < 6 || currentSlide == 5 && $children.length < 11 || currentSlide == 10 && $children.length < 16 || currentSlide == 15 && $children.length < 21)

Any better ideas are welcome.

**Comment by natanv** [comment]
I ran into the same problem.  Here's a better fix, it should work with any moveSlideQty.
Change the same condition

if(currentSlide == lastSlide)

To

if(currentSlide == lastSlide || ( options.moveSlideQty >1 && currentSlide + options.moveSlideQty >= lastSlide))

**Comment by selfthinker** [comment]
Just for the record, these issues are all duplicates: #17, #49, #62, #71 (and probably some more).

**Comment by stevenwanderski** [comment]
Fixed.
