### ISSUE TITLE
Looping the slider causes images to pop in

### ISSUE THREAD

**Issue by bigsweater** [stevenwanderski/bxslider-3#190]
First off, excellent plug-in. It's easy to set up and customize.

But I'm having an issue: when navigating to the last slider from the first (or vice versa), the slide that's being appended pops in--that is to say, there's a blank space, and suddenly the slide appears, but only when the show is looping.

<a href="http://www.moultrietech.edu">For example</a>, when you click the 'prev' arrow here until the slide show loops, you'll see the pop-in that I'm talking about.

Am I making sense? It's not a huge problem, but it's distracting, and detracts from the overall polish of the page.

**Comment by drKnoxy** [comment]
that is an interesting issue, i couldn't debug why it is happening

this is the slide it happened on for me, on chrome
/images/home_carousel/5.jpg

to be fair i haven't seen bxslider implemented this way where it shows part of the other slides.

**Comment by bigsweater** [comment]
Thanks for looking.

You'll see in script.js, I have it set to display three at once, but the pop-in issue persists. I'm working on a site with a similar carousel (where you can peek at previous/next slides) and it has a similar problem. I'm guessing it has to do with the timing of the function that appends slides to the front/rear of the show.

I wrote a custom function to time and control the slides, but I don't think that has anything to do with it, since it uses the public functions in bxSlider.

I may have to man up and roll my own at some point...

**Comment by drKnoxy** [comment]
figured it out, the slide that appears in the "center" is really the far left of the set of three.
let me know if you need more help in correcting it, but that should send you down the right path.

if you take off the css for width and overflow hidden on .hero & .hero .slider you'll see what i mean.

please mark this issue as closed

**Comment by bigsweater** [comment]
Wow. Just a simple CSS fix. I'm not sure why I didn't think to do that before.

I'm not totally sure _why_ that's happening--the CSS that's there is only supposed to shift the .slides div to the right enough so that you can see the preceding slide. I can't figure why I'd have to pull the whole thing to the left one slide's width.

But your fix worked. Thanks!
