### ISSUE TITLE
Dynamically Loading Slide Content: IE issues

### ISSUE THREAD

**Issue by casting989** [stevenwanderski/bxslider-3#20]
In my script, I am dynamically loading the content for the inner slide divs from a mySql database using PHP.

I initialize the slider in the head of the HTML document:

```<script type="text/javascript">
     $('#slider1').bxSlider();
</script>

``````
In the BODY of the document:

```<div id="#slider">
<?
$q = "SELECT * FROM featureContent ORDER BY show_order";
$r = mysql_query($q);
$countrows = mysql_num_rows($r);
if ($countrows != 0) {
    while ( $a = mysql_fetch_assoc($r) ) {
        $title = $a['title'];
        $bodytext = $a['bodytext'];
        echo "<div><h2>" .$title . "</h2>" . $bodytext . "</div>";
    }
}
?>
</div>
``````

This works perfectly in every browser I have tested except IE 8 and earlier.  (Can someone confirm if it works in IE 9+?)  In IE 8, the content does not float left, and instead is stacked vertically, and the paging doesn't work.

I have determined the issue lies in the slider being intialized,  and some reason it doesn't see the dynamically loaded divs.  (I tested manually putting in the content and it works.)  The strange thing is if I have 4 or more slides it works fine...?

Any ideas??

**Comment by steverobertsco** [comment]
This is still an issue, doesn't work with IE8
