### ISSUE TITLE
Multiple sliders with different wrapper layout

### ISSUE THREAD

**Issue by WulleBulle** [stevenwanderski/bxslider-3#201]
Hi,

I can't figure out how to use multiple sliders in a template where every slider has its own individual wrapper layout. Any examples out there?

Thanks, greetings
Wulle

**Comment by KlaasvnA** [comment]
I'm working on an project with lots of sliders:

www.effecty.nl/frontend/oplossingen.html

**Comment by WulleBulle** [comment]
nederlands....thanks but not my language :). Maybe in EN?

**Comment by KlaasvnA** [comment]
The language doesn't realy mather;). You can take a look at the code.

To change the design of the slider you just change the classes and the css:
You have a ul class="slider1" for slider 1

and a ul class="slider2" for slider 2 

For example: to make a second slider with different "next/prev buttons" you change the css for the other slider.

for the first slider: .example1 .bx-next {
background: url(images/next_button_slider1.png);}

and for second slider and .example2 .bxnext {
background: url(images/next_button_slider2.png);} 

Does this help you any further?

**Comment by WulleBulle** [comment]
Yeah, thanks, your link helped me out on doing individual control graphics.
Btw, I was a little disappointed because the thumbnail pager view doesn't allow to scroll the thumbnails by default. By default the thumbnails are listed las standard HTML list and if there are more than a few thumbs the list linebreaks and looks terrible.

I solved it by setting up the thumbnail list as a second bxslider.

```
$('#slider15').bxSlider({
mode: 'horizontal',
infiniteLoop: true,
auto: true,
autoStart: true,
autoDirection: 'next',
autoHover: true,
pause: 3000,
autoControls: false,
pager: true,
pagerCustom: '#pager15',
controls: true,
captions: true,
speed: 500
});
$('#pager15').bxSlider({
mode: 'horizontal',
auto: false,
controls: true,
pager: false,
minSlides: 5,
maxSlides: 5,
moveSlides: 5,
slideWidth: 100
});
```

```
<ul id="slider15">
<li><a href="/internet/horizontal-2" target="_blank"><img src="/content/galleries/15/images/11.jpg" border="0" alt="" title="Dies ist ein Text fuer das Bild." /></a></li>
<li><a href="/internet"><img src="/content/galleries/15/images/21.jpg" border="0" alt="" /></a></li>
<li><a href="/impressum" target="_blank"><img src="/content/galleries/15/images/31.jpg" border="0" alt="" /></a></li>
<li><img src="/content/galleries/15/images/41.jpg" border="0" alt="" /></li>
<li><img src="/content/galleries/15/images/51.jpg" border="0" alt="" /></li>
<li><img src="/content/galleries/15/images/2111.jpg" border="0" alt="" /></li>
<li><img src="/content/galleries/15/images/01511.jpg" border="0" alt="" /></li>
</ul>
<div id="thumbs15">
<div id="pager15">
<a data-slide-index="0"><img src="/content/galleries/15/images/t_11.jpg" border="0" alt="" /></a>
<a data-slide-index="1"><img src="/content/galleries/15/images/t_21.jpg" border="0" alt="" /></a>
<a data-slide-index="2"><img src="/content/galleries/15/images/t_31.jpg" border="0" alt="" /></a>
<a data-slide-index="3"><img src="/content/galleries/15/images/t_41.jpg" border="0" alt="" /></a>
<a data-slide-index="4"><img src="/content/galleries/15/images/t_51.jpg" border="0" alt="" /></a>
<a data-slide-index="5"><img src="/content/galleries/15/images/t_2111.jpg" border="0" alt="" /></a>
<a data-slide-index="6"><img src="/content/galleries/15/images/t_01511.jpg" border="0" alt="" /></a>
</div>
</div>
```

Sorry, HTML code stripped by this (little crappy) editor.
