### ISSUE TITLE
tickerHover not working?

### ISSUE THREAD

**Issue by WulleBulle** [stevenwanderski/bxslider-3#203]
Hiho,

using the following code:

$('#slider15').bxSlider({
mode: 'horizontal',
auto: true,
autoStart: true,
autoDirection: 'next',
minSlides: 4,
maxSlides: 4,
slideWidth: 125,
slideMargin: 4,
ticker: true,
tickerHover: true,
speed: 9000
});

But tickerHover doesn't work. 
Check out the following fiddle to test it:

http://jsfiddle.net/Yq3RM/207/

Bye
Wulle

**Comment by tchailland** [comment]
useCSS must be set to false. That worked for me.
