### ISSUE TITLE
when only 1 element, the slide align it on the right...And for the left ?

### ISSUE THREAD

**Issue by totorche** [stevenwanderski/bxslider-3#208]
Hello,

On this page - http://configurateur.louischevrolet.ch/configurator?aid=32&l=en - when there's only 1 element in the slide, it's placed on the right (look at the "Watch Case" box).

What should I do to align it on the left ?

Thanks a lot...

**Comment by wilson12** [comment]
Now it looks like it aligned to the left?? Have yout fixed it??

**Comment by stevenwanderski** [comment]
This has indeed been fixed! PS - please use the bxSlider v4 repo (https://github.com/wandoledzep/bxslider-4) for all issues.
