### ISSUE TITLE
Touch swipe stops slideshow

### ISSUE THREAD

**Issue by bondimedical3** [stevenwanderski/bxslider-3#248]
I am using BxSlider on CubeCart and every time I use touch swipe to progress through the slide it stops when I am finished and doesn't start again automatically. Is this a bug or can it be adjusted in the settings?

**Comment by jcuenin** [comment]
Hello, I would like to do the same, did you find a way to do it?

**Comment by bondimedical3** [comment]
This is intended behaviour on touch devices

**Comment by jcuenin** [comment]
Yes that's what I understood but I was just wondering if you found a way to change this behaviour anyway.
