### ISSUE TITLE
bxslider freezes browser

### ISSUE THREAD

**Issue by patrickyan** [stevenwanderski/bxslider-3#3]
Tried in Safari, Chrome, Firefox. The spinner will spin and then ask me to kill the page.

If I remove the script, everything works perfectly (except the slider of course).

```
<script src="{$workspace}/js/jquery.bxSlider.min.js" type="text/javascript"></script>
```

I'm using bxSlider (freshly downloaded) with jQuery 1.6.2 (latest). Everything works on my local machine, but after uploading it, I get this problem. If it matters, the host is in China. Totally stumped.

All the scripts that I'm using on the page:

```
<script src="{$workspace}/js/modernizr.js" type="text/javascript"></script>

<script src="{$workspace}/js/jquery.js" type="text/javascript"></script>

<script src="{$workspace}/js/jquery.bxSlider.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function(){

        var slider = $('#slider').bxSlider({
            pager: true,
            pagerSelector: '#my-pager',
            controls: false,
            mode: 'vertical',
            speed: 700,
            auto: true,
            pause: 5000
        });

        $('#go-prev').click(function() {
            slider.goToPreviousSlide();
            return false;
        });

        $('#go-next').click(function() {
            slider.goToNextSlide();
            return false;
        });
    });
</script>
```

Any helps appreciated! If you want to see the live problem: jinhuaguang.com.cn

**Comment by patrickyan** [comment]
The `#slider` was empty. There always needs to be an element inside the slider, otherwise the browser freezes.

**Comment by stevenwanderski** [comment]
Thanks for pointing this out! Fixed.

**Comment by ywarnier** [comment]
As mentioned in the commit, thanks a lot for pointing it out and for fixing it! In Drupal, it so happens that it is apparently possible to generate (somehow) and empty element.
