### ISSUE TITLE
hideControlOnEnd not working with moveSlideQty > 1

### ISSUE THREAD

**Issue by robinll** [stevenwanderski/bxslider-3#49]
I currently have my moveSlideQty set to 6 and hideControlOnEnd set to true.  I have 30 items in my slider, but when I get to items 25 - 30, the 'Next' control is not hidden.  If I change the moveSlideQty to 1 then it works properly.

**Comment by selfthinker** [comment]
Just for the record, these issues are all duplicates: #17, #49, #62, #71 (and probably some more).

**Comment by robinll** [comment]
Thanks.
