### ISSUE TITLE
mode: 'fade' not working

### ISSUE THREAD

**Issue by tracikay** [stevenwanderski/bxslider-3#52]
I have added mode: 'fade' and nothing happens. The pictures don't even show up. When looking at the code everything is there and the transition is occurring, but the area is blank.

Any ideas?

$(function(){
                  $('#HomeSlider').bxSlider({
                    mode: 'fade',
                                        auto: true,
                    controls: false,
                    speed: 1000,
                    pause: 5000
                  });
                });

**Comment by tracikay** [comment]
I forgot to mention, that it works fine and defaults to horizontal scroll when I remove the mode option.

**Comment by am5555** [comment]
Hey tracikay,

Your code is working for me, what html are you using, maybe this will help.

**Comment by NunoBentes** [comment]
Well i´m having exactly the same error. Does anyone knows how to solve it? I´m not sure if this matters, but i´m using HTML5 ...

**Comment by stevemynett** [comment]
I just had the same problem with this. The fix (for me) was adding a hard coded <del>height</del> width for each slide. By default a div will expand to be the width of its parent, but the slider appears to break if this isn't set. Good news, quick fix! :) 

To note, different settings for 'mode' worked fine, this problem appears to just affect mode: "fade", – though I didn't test all of them.

**Comment by tracikay** [comment]
@stevemynett that worked for me too! I want to point out that I did have to set the height to the li. I had first tried the div but it didnt work.

Thank you!

**Comment by rginnow** [comment]
**This comment is for future reference for anyone else getting this problem:**

I just had this problem today using the HTML KickStart by http://www.99lime.com (which requires the `.slideshow` class on the div to show the bxslider) and I had to set the slideshow div height. Upon element inspect in chrome, the div height was 0 (zero) so setting the height did the trick.

**Comment by nnogit** [comment]
I had same issue with floated .bx-wrapper. Works fine without float.

**Comment by taffeld** [comment]
For me I was using it on a WordPress site using the Avada theme and the default fusion builder **column** is set to to "Flex" I had to change it to "Block" then it worked
