### ISSUE TITLE
before the slideshow starts, all slide'images are displayed in a stack, breaking the site's layout for a fraction of second. 

### ISSUE THREAD

**Issue by ilmago** [stevenwanderski/bxslider-3#65]
Congrats for the slideshow, works perfect, but I found this little issue wich makes my slides ugly for a second.
I hope I explained myself well:
I am using the bxslider just to slide images and what happens (all browsers) is that for a fraction of second before the slide starts all images are shown in a stack, totally breaking the layout. 
How can I avoid this?
If you wanna check this behaviour you can see music-selections.com
the slide I am talking about it's right under the header.
thanx very much

**Comment by ankit11** [comment]
I am having a same issue. Site UI looks really bad for a fraction of a time.
I am using ajax to get set of Images to display them in slider. Everything works just perfectly fine but it displays all the images for a second and then works fine. It seems to be a very small problem that i am stuck in but not getting any solution for it. Let me know if anybody has a solution for this.

**Comment by craigmdennis** [comment]
You may need to put a fixed height on your slideshow container with `overflow:hidden;`

So if you're calling BXSlider on `$('#myDiv')` and your images are say 300px in height, then in your CSS do something like

<pre>
#myDiv {
    height:300px;
    overflow:hidden;
}
</pre>

**Comment by ilmago** [comment]
thanx, now it works perfectly
sometimes easiest things never come to mind...

**Comment by koushik1991** [comment]
Thanx.. Its a very good solution..
