### ISSUE TITLE
How to disable and re-enable the plugin?

### ISSUE THREAD

**Issue by pigszel** [stevenwanderski/bxslider-3#78]
Hi guys,

I've got a pretty lame problem. I use bxSlider's ticker mode for a website. It's working great. I have to add a resizer function which changes the width of the visible items.
When I do that, the plugin crashes: it pull the items over each other. So I decided to disable the plugin while I'm resizing the window, set the new width and reactivate the plugin.
But I don't know how to use the public functions. I thought I need reloadShow() which is listed in this page: http://bxslider.com/options

Could anyone help me? I really appreciate it.

**Comment by craigmdennis** [comment]
Give the slideshow a variable name like this `var myTicker =` before you call your slideshow `$('#yourElement').bxSlider(` so it should look like this `var myTicker = $('#yourElement').bxSlider(` and then you can call `myTicker.reloadShow();` or `myTicker.destroyShow();` or any public function.

**Comment by pigszel** [comment]
Oh, that's is! It solved my problem.

Thank you so much!
