### ISSUE TITLE
bxSlider doesn't work within a fancybox

### ISSUE THREAD

**Issue by anrie** [stevenwanderski/bxslider-3#8]
Hey,

i just started using bxSlider for one of my projects and it's really superb.
But i ran into a little problem when i tried to create a slideshow in a fancybox (http://fancybox.net/) modal window.
I tried using the most basic options for bxSlider; just auto:true and pager: true.
The pager gets displayed so the script is obviously called. But no slides are shown.
Looking at the source of the page i noticed: 

```
<div class="bx-wrapper" style="width: 0px; position: relative;"><div class="bx-window" style="position: relative; overflow: hidden; width: 0px;">
```

So the slider seems to calculate the wrong width for the wrapping container.

Is this something that can be fixed on bxSlider's side? Or is this more likely an issue on fancybox's side?

**Comment by stevenwanderski** [comment]
Here's how I got it to work:

HTML:

<pre>
&lt;a href="#fancy-wrap" class="trigger"&gt;launch&lt;/a&gt;

&lt;div style="display:none;"&gt;
    &lt;div id="fancy-wrap"&gt;
        &lt;ul id="main-slider" style="width: 960px;"&gt;
            &lt;li&gt;slide 1&lt;/li&gt;
            &lt;li&gt;slide 2&lt;/li&gt;
            &lt;li&gt;slide 3&lt;/li&gt;
            &lt;li&gt;slide 4&lt;/li&gt;
        &lt;/ul&gt;     
    &lt;/div&gt;
&lt;/div&gt;

</pre>


jQuery:

<pre>
$(function(){   
    var main_slider = $('#main-slider').bxSlider(); 
    $('.trigger').fancybox();       
});
</pre>


CSS:

<pre>
li {
    width: 960px;
}
</pre>


The key is to assign a width to your "slides". In this case, declaring a width to my li's does the trick.

Let me know how it goes.

**Comment by anrie** [comment]
Hooray, that did the trick :-)
Thanks a lot for your quick response!

**Comment by gaiterjones** [comment]
Just experienced exactly this problem today, and your fix no longer works, try it in a jsfiddle and you will see the slider loads but the dimensions are all screwed up and no slide are visible.
