### ISSUE TITLE
Support for Mouse Wheel Scroll?

### ISSUE THREAD

**Issue by nagavardhanraju** [stevenwanderski/bxslider-3#81]
It would be very nice to have mouse wheel scroll support as well. Thanks.

**Comment by fesor** [comment]
You can use <a href="https://github.com/brandonaaron/jquery-mousewheel/blob/master/test/index.html">this</a> plugin for jQuery and use API of BX Slider.

In my opinion such things must be separated.

**Comment by nagavardhanraju** [comment]
Thanks fesor...

**Comment by iDaniel88** [comment]
Using: http://brandonaaron.github.io/jquery-mousewheel/jquery.mousewheel.js 

var slider = $("ul#bxslider").bxSlider();

$('ul#bxslider').mousewheel(function(event, delta, deltaX, deltaY) {
          if (delta > 0) {
              slider.goToPrevSlide();
          }
          if (deltaY < 0){
              slider.goToNextSlide();
          }
          event.stopPropagation();
          event.preventDefault();
});

Works like a charm ;)

**Comment by shahilmhd** [comment]
This is not working with mouse wheel. Any idea what wrong ? I am trying to navigate slider using mouse scroll. 

http://codepen.io/anon/pen/jAvyLm

**Comment by iftimiedaniel** [comment]
Hello shahilmhd, the link for mousewheel.js has changed
Try with this one : https://raw.githubusercontent.com/jquery/jquery-mousewheel/master/jquery.mousewheel.js

**Comment by AbhijithHebbar** [comment]
After The end of bxslider, how to scroll the rest of the page??  without moving the mouse out of the bxslider section

**Comment by iDaniel88** [comment]
In order to scroll your page at the your last slide you need to have "infiniteScroll" set to false on your bxslider settings.
Here is a example, hope it's what you are looking for.

http://codepen.io/anon/pen/xOQQPP

**Comment by AbhijithHebbar** [comment]
Thanks for the replay, Now if we scroll back to first slide, it prevents me scrolling to the upper sections of the page. Please help me out.

**Comment by iDaniel88** [comment]
Hello again,

Simple change on scrolling up.
http://codepen.io/anon/pen/xOQQPP

**Comment by AbhijithHebbar** [comment]
Thank you so much, it works great.

**Comment by AbhijithHebbar** [comment]
Hi,
How to make sure that, it works in touch devices and on scrolling scroll bar???
for example, refer squarespace.com. How to apply that scrolling effect through bx slider.
